name: Issue Forms Dropdown Options
description: Populates options for a version dropdown issue forms element
author: ShaMan123
branding:
  icon: list
  color: purple

inputs:
  github_token:
    description: Github token
    default: ${{ github.token }}
  template:
    description: |
      The location of the template file used to build the form, useful for ease of maintenance.

      Dynamic dropdowns will persist between action runs.
      Static dropdowns (dropdowns with populated options) take precedence over their built counterpart,
      meaning that you should not edit the built form ever,
      see https://github.com/ShaMan123/gha-form-dropdown-options/pull/2/commits/7cbd904caccb60c9bf52f066d11b303e439fe598.

      This behavior makes sense but could have been handled with ease if flagging dynamic dropdowns in forms was possible.
      It might change to a stricter approach in the future using id prefixing.
      It is suggested using the template option once in the first step updating the form and omitting it afterwards.
    type: string
  form:
    description: The location of the yaml form file
    type: string
    required: true
  dropdown:
    description: The id of the dropdown in the yaml form to populate options into
    type: string
    required: true
  options:
    description: A stringified array of options
    type: string
    required: true
  commit_message:
    type: string
    required: true
  dry_run:
    description: When set to `true` will not commit the modified yaml form
    default: false
    type: boolean

# https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs#example-defining-outputs-for-a-job
outputs:
  pushed:
    description: pushed to origin
    value: ${{ steps.commit.outputs.pushed || false }}

runs:
  using: composite
  steps:
    - name: Update ${{ inputs.form }}
      id: process
      run: |
        echo "Updating ${{ inputs.form }}"
        node ${{ github.action_path }}/dist/main.cjs
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        INPUT_TEMPLATE: ${{ inputs.template }}
        INPUT_FORM: ${{ inputs.form }}
        INPUT_DROPDOWN: ${{ inputs.dropdown }}
        INPUT_OPTIONS: ${{ inputs.options }}
        INPUT_COMMIT_MESSAGE: ${{ inputs.commit_message }}
    - name: Commit
      id: commit
      if: ${{ !fromJSON(inputs.dry_run) }}
      run: |
        git config user.name github-actions
        git config user.email noreply@github.com
        git add ${{ inputs.form }}
        UNTRACKED=false
        git diff --staged --quiet || UNTRACKED=true
        if [ $UNTRACKED = true ]; then
          echo "Form ${{ inputs.form }} has been updated"
          echo "Committing ${{ inputs.form }}"
          git commit -m "${{ inputs.commit_message }}"
          git pull --ff-only
          git push
        fi
        echo "::set-output name=pushed::$UNTRACKED"
      # https://askubuntu.com/a/29379
      shell: bash
