name: Issue Forms Version Dropdown
description: Populates options for a version dropdown issue (yaml) form element
author: ShaMan123
branding:
  icon: hash
  color: black
inputs:
  github_token:
    description: Github token
    default: ${{ github.token }}
  form:
    description: 'The location of the yaml form file'
    default: '.github/ISSUE_TEMPLATE/bug_report.yml'
    type: string
  dropdown:
    description: 'The id of the dropdown in the yaml form to populate tags into'
    default: 'version'
    type: string
  package:
    description: 'The name of the published package'
    default: ${{ github.event.repository.name }}
    type: string
  registry:
    description: 'The name of the registry the package is published at'
    default: 'npm'
    type: string
    options:
      - npm
      - github
  order:
    description: 'Display order of populated tags (`asc | desc`)'
    default: 'desc'
    type: choice
    options:
      - desc
      - asc
  limit_to:
    description: 'Limit populated tags'
    type: number
  semver:
    description: 'A semver range query used to filter satisfying tags, see `semver#satisfies`'
    type: string
  tags:
    description: 'A stringified array of tags overriding fetching `package` tags from `registry`, overrides `order`, `limit_to` and dismisses outputs as well'
    type: string
  commit_message:
    default: 'chore(): update bug report version'
    type: string
  dry_run:
    description: When set to `true` will not commit the modified yaml form
    default: false
    type: boolean
outputs:
  # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#example-declaring-outputs-for-composite-actions
  tags:
    description: A stringified array of the resulting tags
    value: ${{ steps.main.outputs.tags }}
  latest:
    description: Latest tag of `package` in `registry`
    value: ${{ steps.main.outputs.latest }}
runs:
  using: composite
  steps:
    # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
    - run: echo "job_ref=${{ github.ref }}" >> $GITHUB_ENV
      shell: bash
    - run: echo "job_ref=${{ github.head_ref }}" >> $GITHUB_ENV
      if: ${{ github.event_name == 'pull_request' }}
      shell: bash
    - run: echo "job_ref=${{ github.event.repository.default_branch }}" >> $GITHUB_ENV
      if: ${{ github.event_name == 'release' }}
      shell: bash
    - uses: actions/checkout@v3
      with:
        ref: ${{ env.job_ref }}
    - name: Update ${{ inputs.form }}
      id: main
      run: node dist/main.cjs
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        INPUT_FORM: ${{ inputs.form }}
        INPUT_DROPDOWN: ${{ inputs.dropdown }}
        INPUT_PACKAGE: ${{ inputs.package }}
        INPUT_REGISTRY: ${{ inputs.registry }}
        INPUT_ORDER: ${{ inputs.order }}
        INPUT_LIMIT_TO: ${{ inputs.limit_to }}
        INPUT_SEMVER: ${{ inputs.semver }}
        INPUT_TAGS: ${{ inputs.tags }}
        INPUT_COMMIT_MESSAGE: ${{ inputs.commit_message }}
    - name: Commit to ${{ env.job_ref }}
      if: ${{ !fromJSON(inputs.dry_run) }}
      run: |
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git add ${{ inputs.form }}
        git diff --staged --quiet || git commit -m "${{ inputs.commit_message }}"
        git push
      shell: bash
