name: Issue Forms Dropdown Options
description: Populates options for a version dropdown issue (yaml) form element
author: ShaMan123
branding:
  icon: list
  color: purple
inputs:
  github_token:
    description: Github token
    default: ${{ github.token }}
  ref:
    description: Github ref/branch to update, inferred from the event type if omitted
    type: string
  template:
    description: |
      The location of the template file used to build the form, useful for ease of maintenance.

      Dynamic dropdowns will persist between action runs.
      Static dropdowns (dropdowns with populated options) take precedence over their built counterpart,
      meaning that you should not edit the built form ever,
      see https://github.com/ShaMan123/gha-form-dropdown-options/pull/2/commits/7cbd904caccb60c9bf52f066d11b303e439fe598.

      This behavior makes sense but could have been handled with ease if flagging dynamic dropdowns in forms was possible.
    type: string
  form:
    description: The location of the yaml form file
    default: '.github/ISSUE_TEMPLATE/bug_report.yml'
    type: string
  dropdown:
    description: The id of the dropdown in the yaml form to populate options into
    type: string
  options:
    description: A stringified array of options
    type: string
  commit_message:
    type: string
  dry_run:
    description: When set to `true` will not commit the modified yaml form
    default: false
    type: boolean
outputs:
  ref:
    description: Github ref/branch checked out and updated by the action
    value: ${{ env.job_ref }}
runs:
  using: composite
  steps:
    # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
    - run: echo "Setting branch for action"
      shell: bash
    - run: echo "job_ref=${{ github.ref }}" >> $GITHUB_ENV
      shell: bash
    - run: echo "job_ref=${{ github.head_ref }}" >> $GITHUB_ENV
      if: ${{ github.event_name == 'pull_request' }}
      shell: bash
    - run: echo "job_ref=${{ github.event.repository.default_branch }}" >> $GITHUB_ENV
      if: ${{ github.event_name == 'release' }}
      shell: bash
    - run: echo "job_ref=${{ inputs.ref }}" >> $GITHUB_ENV
      if: ${{ inputs.ref }}
      shell: bash
    - uses: actions/checkout@v3
      with:
        ref: ${{ env.job_ref }}
    - name: Update ${{ inputs.form }}
      id: main
      run: |
        echo "Updating ${{ inputs.form }}"
        node ${{ github.action_path }}/dist/main.cjs
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        INPUT_TEMPLATE: ${{ inputs.template }}
        INPUT_FORM: ${{ inputs.form }}
        INPUT_DROPDOWN: ${{ inputs.dropdown }}
        INPUT_OPTIONS: ${{ inputs.options }}
        INPUT_COMMIT_MESSAGE: ${{ inputs.commit_message }}
    - name: Commit to ${{ env.job_ref }}
      if: ${{ !fromJSON(inputs.dry_run) }}
      run: |
        echo "Committing ${{ inputs.form }} to ${{ env.job_ref }}"
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git add ${{ inputs.form }}
        git diff --staged --quiet || git commit -m "${{ inputs.commit_message }}"
        git pull
        git push
      shell: bash
