name: 🐛 Bug Report
description: File a bug report
title: '[Bug]: '
body:
  - type: markdown
    attributes:
      value: |
        Before you begin
  - type: checkboxes
    id: terms
    attributes:
      label: CheckList
      description: By submitting this issue, you agree to follow our [Code of Conduct]()
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: dropdown
    id: _branches
    attributes:
      label: Repository Branches
      description: Fetched by action
      options:
        - ci-update-long-report
        - main
        - safeguard
        - set-output
    validations:
      required: true
  - type: dropdown
    id: _labels
    attributes:
      label: Repository labels
      description: Fetched by action
      options:
        - bot
        - bug
        - ci
        - documentation
        - duplicate
        - enhancement
        - good first issue
        - help wanted
        - invalid
        - question
        - wontfix
    validations:
      required: true
  - type: dropdown
    id: _dates
    attributes:
      label: Updating Dates
      description: Choose a day next week
      options:
        - 2024-4-17
        - 2024-4-18
        - 2024-4-19
        - 2024-4-20
        - 2024-4-21
        - 2024-4-22
        - 2024-4-23
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      value: |
        1. 
        2. 
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Provide screenshots/screencasts if relevant
    validations:
      required: true
  - type: textarea
    id: error
    attributes:
      label: Error Message & Stack Trace
      description: Provide logging outputs/errors if relevant
    validations:
      required: false
