name: 🐛 Bug Report
description: File a bug report
title: '[Bug]: '
body:
  - type: markdown
    attributes:
      value: |
        Before you begin
  - type: checkboxes
    id: terms
    attributes:
      label: CheckList
      description: By submitting this issue, you agree to follow our [Code of Conduct]()
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: dropdown
    id: branches
    attributes:
      label: Repository Branches
      description: Fetched by action
      options:
        - main
    validations:
      required: true
  - type: dropdown
    id: labels
    attributes:
      label: Repository labels
      description: Fetched by action
      options:
        - template
    validations:
      required: true
  - type: dropdown
    id: dates
    attributes:
      label: Updating Dates
      description: Choose a day next week
      options:
        - '2022-10-05'
        - '2022-10-06'
        - '2022-10-07'
        - '2022-10-08'
        - '2022-10-09'
        - '2022-10-10'
        - '2022-10-11'
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      value: |
        1. 
        2. 
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Provide screenshots/screencasts if relevant
    validations:
      required: true
  - type: textarea
    id: error
    attributes:
      label: Error Message & Stack Trace
      description: Provide logging outputs/errors if relevant
    validations:
      required: false
