name: 🚀 Update Bug Report

on:
  # used for testing this action
  # you shouldn't use this trigger in production
  push:
    branches:
      - main

  # used for testing this action
  # you shouldn't use this trigger in production
  pull_request:
    branches: [main]

  workflow_dispatch:

  # use in production
  release:
    branches:
      - main
    types: [published]

  # use in production
  schedule:
    # runs daily at midnight
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '0 0 * * *'

jobs:
  update-bug-report:
    runs-on: ubuntu-latest
    name: Update bug report
    steps:
      - uses: actions/checkout@v3
      - name: Get branches
        id: branches
        # https://github.com/actions/github-script
        uses: actions/github-script@v6
        with:
          script: |
            github
              .getOctokit()
              .rest.repos.listBranches(github.context.repo)
              .then((res) => res.data.map((b) => b.name));
      - name: Update branches
        uses: ./
        with:
          dropdown: branches
          options: ${{ steps.branches.result }}

      - name: Get next week
        id: dates
        # https://github.com/actions/github-script
        uses: actions/github-script@v6
        with:
          script: |
            import moment from 'moment';
            return new array(7).fill(0)
              .map((_, i) => moment().add(i + 7, 'd').format('YYYY-MM-DD'));
      - name: Update dates
        id: update_dates
        uses: ./
        with:
          dropdown: dates
          options: ${{ steps.dates.result }}
